import type { Segment, Transcript } from '../types.js';

/**
 * Bump when the output layout changes. The version is part of the content hash,
 * so a bump makes the next sync rewrite every source once.
 */
export const FORMAT_VERSION = 1;

/** Chatbase text sources accept at most 1,048,576 characters. Keep headroom for the header. */
export const MAX_SOURCE_CHARS = 1_040_000;

export function clock(sec: number): string {
  const s = Math.max(0, Math.floor(sec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const r = s % 60;
  const mm = String(m).padStart(h ? 2 : 1, '0');
  return h ? `${h}:${mm}:${String(r).padStart(2, '0')}` : `${mm}:${String(r).padStart(2, '0')}`;
}

export interface Chapter {
  start: number;
  title: string;
}

/**
 * YouTube chapters live in the description as lines that start with a timestamp.
 * They only count when the first is 0:00 and there are at least three (YouTube's own rule).
 */
export function parseChapters(description: string | undefined): Chapter[] {
  if (!description) return [];
  const out: Chapter[] = [];
  for (const line of description.split(/\r?\n/)) {
    const m = line.match(/^\s*[[(]?((?:\d{1,2}:)?\d{1,2}:\d{2})[\])]?\s*[-–—:|]?\s+(.+?)\s*$/);
    if (!m) continue;
    const parts = m[1]!.split(':').map(Number);
    const start = parts.reduce((acc, n) => acc * 60 + n, 0);
    out.push({ start, title: m[2]! });
  }
  if (out.length < 3 || out[0]!.start !== 0) return [];
  for (let i = 1; i < out.length; i++) if (out[i]!.start <= out[i - 1]!.start) return [];
  return out;
}

const SENTENCE_END = /[.!?…]["')\]]?$/;
const NOISE = /\[(?:music|applause|laughter|inaudible)\]|\((?:music|applause|laughter)\)/gi;

function clean(text: string): string {
  return text.replace(NOISE, ' ').replace(/\s+/g, ' ').trim();
}

export interface Block {
  start: number;
  end: number;
  heading?: string;
  text: string;
}

/**
 * Merge caption segments into readable blocks of about `windowSec` seconds.
 * A block closes at the first sentence end after the window is reached, or at
 * 1.5x the window regardless, so one block never grows unbounded. Chapter
 * boundaries always start a new block.
 */
export function toBlocks(segments: Segment[], windowSec: number, chapters: Chapter[] = []): Block[] {
  const blocks: Block[] = [];
  let cur: { start: number; end: number; parts: string[]; heading?: string } | undefined;
  let chapterIdx = -1;
  const chapterAt = (t: number): number => {
    let idx = -1;
    for (let i = 0; i < chapters.length; i++) if (chapters[i]!.start <= t + 0.5) idx = i;
    return idx;
  };
  const flush = (): void => {
    if (!cur) return;
    const text = clean(cur.parts.join(' '));
    if (text) blocks.push({ start: cur.start, end: cur.end, heading: cur.heading, text });
    cur = undefined;
  };
  for (const seg of segments) {
    const text = clean(seg.text);
    if (!text) continue;
    const ch = chapterAt(seg.start);
    if (ch !== chapterIdx) {
      flush();
      chapterIdx = ch;
    }
    if (!cur) cur = { start: seg.start, end: seg.end, parts: [], heading: ch >= 0 ? chapters[ch]!.title : undefined };
    cur.parts.push(text);
    cur.end = Math.max(cur.end, seg.end);
    const span = cur.end - cur.start;
    if ((span >= windowSec && SENTENCE_END.test(text)) || span >= windowSec * 1.5) flush();
  }
  flush();
  return blocks;
}

export function timeLink(videoId: string, sec: number): string {
  return `https://youtu.be/${videoId}?t=${Math.max(0, Math.floor(sec))}`;
}

/** Render one video as Markdown text. Returns one or more parts, each within the size limit. */
export function formatTranscript(t: Transcript, windowSec: number): string[] {
  const chapters = parseChapters(t.description);
  const blocks = toBlocks(t.segments, windowSec, chapters);
  const meta = [
    t.channel ? `Channel: ${t.channel}` : undefined,
    t.publishedAt ? `Published: ${t.publishedAt}` : undefined,
    t.durationSec !== undefined ? `Duration: ${clock(t.durationSec)}` : undefined,
    t.language ? `Language: ${t.language}` : undefined,
    t.isAiGenerated ? 'Transcript: AI speech-to-text' : t.isAutoGenerated ? 'Transcript: auto-generated captions' : undefined,
  ].filter(Boolean);
  const header = [
    `# ${t.title} (video)`,
    meta.join(' · '),
    `URL: https://www.youtube.com/watch?v=${t.id}`,
    'When you answer from this video, link the timestamp of the section you used.',
  ]
    .filter(Boolean)
    .join('\n');

  const sections = blocks.map((b) => {
    const label = `${clock(b.start)}–${clock(b.end)}`;
    const title = b.heading ? `${b.heading} · ${label}` : label;
    return `## ${title} · [watch](${timeLink(t.id, b.start)})\n${b.text}`;
  });

  const parts: string[] = [];
  let buf = header;
  for (const s of sections) {
    if (buf.length + s.length + 2 > MAX_SOURCE_CHARS && buf !== header) {
      parts.push(buf);
      buf = `${header}\n(continued)`;
    }
    buf += `\n\n${s}`;
  }
  parts.push(buf);
  return parts;
}
