// Transcript provider backed by an Apify Actor (default: codepoetry/youtube-transcript-ai-scraper).
// Talks to the Apify REST API directly, so there is no SDK in the supply chain.

import { HttpError, UserError, ExitCode } from '../util/errors.js';
import { readJson, withRetry, sleep, type FetchFn } from '../util/http.js';
import { log } from '../util/log.js';
import { parseVideoId, type Transcript, type TranscriptFailure } from '../types.js';

const API = 'https://api.apify.com/v2';

export interface TranscribeOptions {
  languages: string[];
  machineTranslate: boolean;
  ai: { enabled: boolean; maxMinutesPerRun: number; skipLongerThanMin: number; language?: string };
  /** For channel/playlist URLs: how many videos to return. */
  maxResults?: number;
}

export interface TranscribeResult {
  transcripts: Transcript[];
  failures: TranscriptFailure[];
  runId?: string;
  usageUsd?: number;
}

interface ActorItem {
  url?: string;
  error_code?: string;
  error?: string;
  metadata?: {
    id?: string;
    title?: string;
    url?: string;
    description?: string;
    duration?: number;
    channel?: string;
    upload_date?: string;
  };
  language?: string;
  is_auto_generated?: boolean;
  is_ai_generated?: boolean;
  transcript_json?: Array<{ start: number; end: number; text: string }>;
  transcript_llm?: string;
  transcript_text?: string;
}

interface RunData {
  id: string;
  status: string;
  defaultDatasetId: string;
  usageTotalUsd?: number;
}

export function mapItem(it: ActorItem): Transcript | TranscriptFailure | undefined {
  const id = it.metadata?.id ?? parseVideoId(it.metadata?.url ?? it.url ?? '');
  if (!id) return undefined;
  if (it.error_code || !it.transcript_json) {
    return { id, code: it.error_code ?? 'NO_TRANSCRIPT', message: it.error ?? 'no transcript returned' };
  }
  const ud = it.metadata?.upload_date;
  return {
    id,
    title: it.metadata?.title ?? id,
    url: it.metadata?.url ?? `https://www.youtube.com/watch?v=${id}`,
    channel: it.metadata?.channel,
    publishedAt: ud && /^\d{8}$/.test(ud) ? `${ud.slice(0, 4)}-${ud.slice(4, 6)}-${ud.slice(6, 8)}` : undefined,
    durationSec: it.metadata?.duration,
    language: it.language,
    isAutoGenerated: it.is_auto_generated,
    isAiGenerated: it.is_ai_generated,
    description: it.metadata?.description,
    segments: it.transcript_json,
    text: it.transcript_llm ?? it.transcript_text ?? it.transcript_json.map((s) => s.text).join(' '),
  };
}

export class ApifyTranscriptProvider {
  constructor(
    private readonly token: string,
    private readonly actorId: string,
    private readonly build?: string,
    private readonly fetchFn: FetchFn = fetch,
    private readonly pollMs = 5_000,
    private readonly timeoutMs = 60 * 60_000,
  ) {}

  private headers(): Record<string, string> {
    if (!this.token) throw new UserError('APIFY_TOKEN is not set', ExitCode.AuthOrPlan);
    return { authorization: `Bearer ${this.token}`, 'content-type': 'application/json' };
  }

  private actorPath(): string {
    return encodeURIComponent(this.actorId.replace('/', '~'));
  }

  /** Check the token and the Actor are reachable. Used by `doctor`. */
  async check(): Promise<{ user: string; actor: string }> {
    const me = await readJson<{ data: { username: string } }>(
      await this.fetchFn(`${API}/users/me`, { headers: this.headers() }),
      'Apify users/me',
    );
    const act = await readJson<{ data: { name: string; username: string } }>(
      await this.fetchFn(`${API}/acts/${this.actorPath()}`, { headers: this.headers() }),
      `Apify actor ${this.actorId}`,
    );
    return { user: me.data.username, actor: `${act.data.username}/${act.data.name}` };
  }

  async transcribe(urls: string[], opts: TranscribeOptions): Promise<TranscribeResult> {
    if (urls.length === 0) return { transcripts: [], failures: [] };
    const input = {
      startUrls: urls.map((url) => ({ url })),
      maxResults: opts.maxResults ?? 10,
      languages: opts.languages,
      machineTranslateCaptions: opts.machineTranslate,
      outputFormats: ['json', 'llm'],
      enableAiFallback: opts.ai.enabled,
      maxAiMinutes: opts.ai.maxMinutesPerRun,
      skipAiFallbackIfLongerThan: opts.ai.skipLongerThanMin,
      ...(opts.ai.language ? { forceTranscriptionLanguage: opts.ai.language } : {}),
    };
    const qs = this.build ? `?build=${encodeURIComponent(this.build)}` : '';
    const started = await withRetry('apify start run', async () =>
      readJson<{ data: RunData }>(
        await this.fetchFn(`${API}/acts/${this.actorPath()}/runs${qs}`, {
          method: 'POST',
          headers: this.headers(),
          body: JSON.stringify(input),
        }),
        `Apify start ${this.actorId}`,
      ),
    );
    let run = started.data;
    log.info('apify run started', { runId: run.id, videos: urls.length });

    const deadline = Date.now() + this.timeoutMs;
    while (!['SUCCEEDED', 'FAILED', 'ABORTED', 'TIMED-OUT'].includes(run.status)) {
      if (Date.now() > deadline) throw new UserError(`Apify run ${run.id} did not finish in time`);
      await sleep(this.pollMs);
      run = (
        await withRetry('apify poll run', async () =>
          readJson<{ data: RunData }>(
            await this.fetchFn(`${API}/actor-runs/${run.id}`, { headers: this.headers() }),
            `Apify run ${run.id}`,
          ),
        )
      ).data;
    }
    if (run.status !== 'SUCCEEDED') {
      throw new HttpError(502, run.status, `Apify run ${run.id} ended with status ${run.status}`);
    }

    const transcripts: Transcript[] = [];
    const failures: TranscriptFailure[] = [];
    const limit = 100;
    for (let offset = 0; ; offset += limit) {
      const items = await withRetry('apify dataset page', async () =>
        readJson<ActorItem[]>(
          await this.fetchFn(
            `${API}/datasets/${run.defaultDatasetId}/items?clean=true&format=json&offset=${offset}&limit=${limit}`,
            { headers: this.headers() },
          ),
          'Apify dataset',
        ),
      );
      for (const it of items) {
        const m = mapItem(it);
        if (!m) continue;
        if ('segments' in m) transcripts.push(m);
        else failures.push(m);
      }
      if (items.length < limit) break;
    }
    log.info('apify run finished', {
      runId: run.id,
      transcripts: transcripts.length,
      failures: failures.length,
      usageUsd: run.usageTotalUsd,
    });
    return { transcripts, failures, runId: run.id, usageUsd: run.usageTotalUsd };
  }
}
