export interface VideoRef {
  id: string;
  title?: string;
  /** YYYY-MM-DD */
  publishedAt?: string;
  isShort?: boolean;
}

export interface Segment {
  start: number;
  end: number;
  text: string;
}

export interface Transcript {
  id: string;
  title: string;
  url: string;
  channel?: string;
  /** YYYY-MM-DD */
  publishedAt?: string;
  durationSec?: number;
  language?: string;
  isAutoGenerated?: boolean;
  isAiGenerated?: boolean;
  description?: string;
  segments: Segment[];
  text: string;
}

export interface TranscriptFailure {
  id: string;
  code: string;
  message: string;
}

/** One knowledge source we own in Chatbase (or one exported file). */
export interface OwnedSource {
  sourceId: string;
  videoId: string;
  hash: string;
  part: number;
  name: string;
  size: number;
  status?: string;
}

const ID_RE = /^[A-Za-z0-9_-]{11}$/;

export function isVideoId(s: string): boolean {
  return ID_RE.test(s);
}

/** Extract an 11-character video ID from any common YouTube URL form, or a bare ID. */
export function parseVideoId(input: string): string | undefined {
  const s = input.trim();
  if (ID_RE.test(s)) return s;
  let u: URL;
  try {
    u = new URL(s);
  } catch {
    return undefined;
  }
  const host = u.hostname.replace(/^www\.|^m\./, '');
  if (host === 'youtu.be') {
    const id = u.pathname.slice(1).split('/')[0] ?? '';
    return ID_RE.test(id) ? id : undefined;
  }
  if (host === 'youtube.com' || host === 'music.youtube.com') {
    const v = u.searchParams.get('v');
    if (v && ID_RE.test(v)) return v;
    const m = /^\/(?:shorts|embed|live|v)\/([A-Za-z0-9_-]{11})/.exec(u.pathname);
    if (m) return m[1];
  }
  return undefined;
}

export function watchUrl(id: string): string {
  return `https://www.youtube.com/watch?v=${id}`;
}
